<link rel="stylesheet" type="text/css" href="css.css">.
<?php

//Defines products in array
//Array records the product's number, description, and price
$product1 = array('number' => 1,
    'desc' => 'Gold Standard Whey Protein - French Vanilla',
    'price' => 69.99);

$product2 = array('number' => 2,
    'desc' => 'C4 Pre-Workout - Icy Blue Razz',
    'price' => 34.99);

$product3 = array('number' => 3,
    'desc' => 'Pure Protein Bar - Chocolate Peanut Butter',
    'price' => 19.99);

$product4 = array('number' => 4,
    'desc' => 'Pure Protein Bar - Chocolate Deluxe',
    'price' => 22.99);

$product5 = array('number' => 5,
    'desc' => 'Optimum Nutrition Creatine',
    'price' => 44.99);

$product6 = array('number' => 6,
    'desc' => 'Gold Standard Whey Protein - Mocha Cappuccino',
    'price' => 64.99);

$product7 = array('number' => 7,
    'desc' => 'Gold Standard Whey Protein - Double Chocolate',
    'price' => 59.99);

$product8 = array('number' => 8,
    'desc' => 'C4 Pre-Workout - Pink Lemonade',
    'price' => 29.99);

$product9 = array('number' => 9,
    'desc' => 'C4 Pre-Workout - Fruit Punch',
    'price' => 29.99);

//Multi-dimensional array to store all of the individual products listed above
$products = array($product1, $product2, $product3, $product4, $product5, $product6, $product7, $product8, $product9);
?>
